"""Initial migration

Revision ID: c9da53f54cbd
Revises:
Create Date: 2026-10-04 14:40:14.149386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9da53f54cbd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-incrementing primary key'),
    sa.Column('account', sa.String(length=64), nullable=False, comment='Unique login account'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='Password hash; never plaintext'),
    sa.Column('createtime', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp when the record was created'),
    sa.Column('updatetime', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account', name='uq_auth_user_account')
    )
    op.create_table('portfolio_career',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='Shared Journey / Experience ID'),
    sa.Column('journey_position', sa.Integer(), nullable=False, comment='Journey array order, starting at zero'),
    sa.Column('experience_order', sa.Float(), nullable=False, comment='Experience order value returned by the API'),
    sa.Column('country_code', sa.String(length=3), nullable=False, comment='ISO alpha-3 code used by the world map'),
    sa.Column('latitude', sa.Float(), nullable=False, comment='Map latitude in degrees'),
    sa.Column('longitude', sa.Float(), nullable=False, comment='Map longitude in degrees'),
    sa.Column('type', sa.String(length=16), nullable=False, comment='work or education'),
    sa.Column('start_month', sa.Date(), nullable=False, comment='First day of start month; API formats YYYY-MM'),
    sa.Column('end_month', sa.Date(), nullable=True, comment='First day of end month; null means ongoing'),
    sa.Column('end_day', sa.Integer(), nullable=True, comment='Optional actual day within end_month'),
    sa.Column('expected', sa.Boolean(), nullable=False, comment='Whether the period is expected'),
    sa.Column('detail_start_month', sa.Date(), nullable=True, comment='Optional detail period start month'),
    sa.Column('detail_end_month', sa.Date(), nullable=True, comment='Optional detail period end month'),
    sa.Column('detail_end_day', sa.Integer(), nullable=True, comment='Optional actual day within detail_end_month'),
    sa.CheckConstraint("type IN ('work', 'education')", name='ck_portfolio_career_type'),
    sa.CheckConstraint('detail_end_day IS NULL OR detail_end_month IS NOT NULL AND detail_end_day BETWEEN 1 AND 31', name='ck_portfolio_career_detail_end_day'),
    sa.CheckConstraint('detail_end_month IS NULL OR detail_end_month >= detail_start_month', name='ck_portfolio_career_detail_months'),
    sa.CheckConstraint('detail_start_month IS NOT NULL OR detail_end_month IS NULL', name='ck_portfolio_career_detail_start'),
    sa.CheckConstraint('end_day IS NULL OR end_month IS NOT NULL AND end_day BETWEEN 1 AND 31', name='ck_portfolio_career_end_day'),
    sa.CheckConstraint('end_month IS NULL OR end_month >= start_month', name='ck_portfolio_career_months'),
    sa.CheckConstraint('id BETWEEN 1 AND 9007199254740991', name='ck_portfolio_career_safe_id'),
    sa.CheckConstraint('journey_position >= 0', name='ck_portfolio_career_journey_position'),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='ck_portfolio_career_latitude'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='ck_portfolio_career_longitude'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journey_position', name='uq_portfolio_career_journey_position')
    )
    op.create_index('ix_portfolio_career_experience_order', 'portfolio_career', ['experience_order', 'id'], unique=False)
    op.create_table('portfolio_locale',
    sa.Column('code', sa.String(length=32), nullable=False, comment='Language tag, e.g. en or zh-Hant'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='Language self-name, e.g. English or 繁體中文'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the API accepts this language'),
    sa.CheckConstraint("code != ''", name='ck_portfolio_locale_code'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('portfolio_project',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='Project API ID'),
    sa.Column('position', sa.Integer(), nullable=False, comment='Project array order, starting at zero'),
    sa.Column('start_month', sa.Date(), nullable=False, comment='First day of project start month; API formats YYYY-MM'),
    sa.Column('end_month', sa.Date(), nullable=True, comment='First day of project end month; null means ongoing'),
    sa.Column('expected', sa.Boolean(), nullable=False, comment='Whether the project period is expected'),
    sa.CheckConstraint('end_month IS NULL OR end_month >= start_month', name='ck_portfolio_project_months'),
    sa.CheckConstraint('NOT expected OR end_month IS NOT NULL', name='ck_portfolio_project_expected'),
    sa.CheckConstraint('id BETWEEN 1 AND 9007199254740991', name='ck_portfolio_project_safe_id'),
    sa.CheckConstraint('position >= 0', name='ck_portfolio_project_position'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position', name='uq_portfolio_project_position')
    )
    op.create_table('portfolio_site',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-incrementing primary key'),
    sa.Column('copyright_year', sa.Integer(), nullable=False, comment='Explicit copyright year; not calculated from the clock'),
    sa.Column('linkedin', sa.String(length=2048), nullable=False, comment='LinkedIn URL; empty string hides the link'),
    sa.Column('github', sa.String(length=2048), nullable=False, comment='GitHub URL; empty string hides the link'),
    sa.Column('medium', sa.String(length=2048), nullable=False, comment='Medium URL; empty string hides the link'),
    sa.Column('email', sa.String(length=320), nullable=False, comment='Email address without mailto:'),
    sa.Column('chat_icon', sa.String(length=512), nullable=False, comment='Relative path to the bundled chat icon'),
    sa.CheckConstraint('copyright_year >= 0', name='ck_portfolio_site_copyright_year'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_skill',
    sa.Column('id', sa.String(length=128), nullable=False, comment='Skill slug returned by the API'),
    sa.Column('label_key', sa.String(length=255), nullable=False, comment='Translation key, e.g. skill.python'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label_key')
    )
    op.create_table('portfolio_skill_category',
    sa.Column('id', sa.String(length=128), nullable=False, comment='Category slug returned by the API'),
    sa.Column('label_key', sa.String(length=255), nullable=False, comment='Translation key for the category label'),
    sa.Column('position', sa.Integer(), nullable=False, comment='Category array order, starting at zero'),
    sa.CheckConstraint('position >= 0', name='ck_portfolio_skill_category_position'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label_key'),
    sa.UniqueConstraint('position', name='uq_portfolio_skill_category_position')
    )
    op.create_table('portfolio_career_locale',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-incrementing primary key'),
    sa.Column('career_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='Shared career record'),
    sa.Column('locale', sa.String(length=32), nullable=False, comment='Language code'),
    sa.Column('country_name', sa.String(length=255), nullable=False, comment='Localized country display name'),
    sa.Column('city', sa.String(length=255), nullable=False, comment='Localized city display name'),
    sa.Column('organization_name', sa.String(length=255), nullable=False, comment='Localized organization display name'),
    sa.Column('organization_code', sa.String(length=255), nullable=False, comment='Localized display abbreviation; not a foreign key'),
    sa.Column('organization_title', sa.String(length=255), nullable=False, comment='Localized role or academic program'),
    sa.Column('content', sa.Text(), nullable=False, comment='Experience summary'),
    sa.Column('skills', sa.JSON(), nullable=False, comment='Ordered, localized experience skill labels as a string array'),
    sa.Column('detail_content', sa.Text(), nullable=True, comment='Journey / Experience detail content; null when there is no detail'),
    sa.Column('content_blocks', sa.JSON(), nullable=True, comment='Optional localized sections beyond the current career API'),
    sa.ForeignKeyConstraint(['career_id'], ['portfolio_career.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['locale'], ['portfolio_locale.code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_id', 'locale', name='uq_portfolio_career_locale')
    )
    op.create_table('portfolio_category_skill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-incrementing primary key'),
    sa.Column('category_id', sa.String(length=128), nullable=False, comment='Category slug'),
    sa.Column('skill_id', sa.String(length=128), nullable=False, comment='Skill slug'),
    sa.Column('position', sa.Integer(), nullable=False, comment='Skill order inside the category, starting at zero'),
    sa.CheckConstraint('position >= 0', name='ck_portfolio_category_skill_position'),
    sa.ForeignKeyConstraint(['category_id'], ['portfolio_skill_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['portfolio_skill.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'position', name='uq_portfolio_category_skill_position'),
    sa.UniqueConstraint('category_id', 'skill_id', name='uq_portfolio_category_skill')
    )
    op.create_table('portfolio_project_locale',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-incrementing primary key'),
    sa.Column('project_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='Project record'),
    sa.Column('locale', sa.String(length=32), nullable=False, comment='Language code'),
    sa.Column('organization_name', sa.String(length=255), nullable=False, comment='Localized organization display name'),
    sa.Column('organization_code', sa.String(length=255), nullable=False, comment='Localized display abbreviation; not a foreign key'),
    sa.Column('organization_title', sa.String(length=255), nullable=False, comment='Localized role or academic program'),
    sa.Column('project_name', sa.String(length=255), nullable=False, comment='Project name'),
    sa.Column('project_title', sa.String(length=255), nullable=False, comment='Project category heading'),
    sa.Column('intro', sa.Text(), nullable=False, comment='Short project introduction'),
    sa.Column('skills', sa.JSON(), nullable=True, comment='Ordered, localized skill-label array; null is distinct from []'),
    sa.Column('detail_kind', sa.String(length=8), nullable=False, comment='API detail representation: object, null or empty'),
    sa.Column('workflow_description', sa.Text(), nullable=True, comment='Detail workflowDescription'),
    sa.Column('flow', sa.JSON(), nullable=True, comment='Ordered flow string array; null is distinct from []'),
    sa.Column('technical_description', sa.Text(), nullable=True, comment='Detail technicalDescription'),
    sa.Column('contribution', sa.Text(), nullable=True, comment='Detail contribution'),
    sa.Column('outcome', sa.Text(), nullable=True, comment='Detail outcome'),
    sa.Column('content_blocks', sa.JSON(), nullable=True, comment='Optional localized sections beyond the current project API'),
    sa.CheckConstraint("detail_kind IN ('object', 'null', 'empty')", name='ck_portfolio_project_detail_kind'),
    sa.ForeignKeyConstraint(['locale'], ['portfolio_locale.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['portfolio_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'locale', name='uq_portfolio_project_locale')
    )
    op.create_table('portfolio_site_locale',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-incrementing primary key'),
    sa.Column('site_id', sa.Integer(), nullable=False, comment='Site record'),
    sa.Column('locale', sa.String(length=32), nullable=False, comment='Language code'),
    sa.Column('brand_title', sa.String(length=255), nullable=False, comment='Brand title'),
    sa.Column('brand_title_sub', sa.String(length=255), nullable=False, comment='Brand subtitle; independent of nickname'),
    sa.Column('first_name', sa.String(length=255), nullable=False, comment='Profile given name'),
    sa.Column('family_name', sa.String(length=255), nullable=False, comment='Profile family name'),
    sa.Column('nick_name', sa.String(length=255), nullable=False, comment='Accessible home-label nickname'),
    sa.Column('profile_content', sa.Text(), nullable=False, comment='Profile introduction and meta description'),
    sa.Column('edu_code', sa.String(length=128), nullable=False, comment='Education display abbreviation; not a foreign key'),
    sa.Column('program', sa.String(length=255), nullable=False, comment='Education program'),
    sa.Column('intro_content', sa.Text(), nullable=False, comment='Introduction above the name'),
    sa.Column('footer_content', sa.Text(), nullable=False, comment='Footer tagline'),
    sa.Column('chat_title', sa.String(length=255), nullable=False, comment='Chat title'),
    sa.Column('chat_title_sub', sa.String(length=255), nullable=False, comment='Chat subtitle'),
    sa.Column('chat_content', sa.Text(), nullable=False, comment='Chat copy, including paragraph newlines'),
    sa.Column('content_blocks', sa.JSON(), nullable=True, comment='Optional localized sections beyond the current site API'),
    sa.ForeignKeyConstraint(['locale'], ['portfolio_locale.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['portfolio_site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'locale', name='uq_portfolio_site_locale')
    )
    op.create_table('portfolio_skill_category_locale',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-incrementing primary key'),
    sa.Column('category_id', sa.String(length=128), nullable=False, comment='Category slug'),
    sa.Column('locale', sa.String(length=32), nullable=False, comment='Language code'),
    sa.Column('label', sa.String(length=255), nullable=False, comment='Localized label for label_key'),
    sa.ForeignKeyConstraint(['category_id'], ['portfolio_skill_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['locale'], ['portfolio_locale.code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'locale', name='uq_portfolio_skill_category_locale')
    )
    op.create_table('portfolio_skill_locale',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-incrementing primary key'),
    sa.Column('skill_id', sa.String(length=128), nullable=False, comment='Skill slug'),
    sa.Column('locale', sa.String(length=32), nullable=False, comment='Language code'),
    sa.Column('label', sa.String(length=255), nullable=False, comment='Localized label for label_key'),
    sa.ForeignKeyConstraint(['locale'], ['portfolio_locale.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['portfolio_skill.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'locale', name='uq_portfolio_skill_locale')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_skill_locale')
    op.drop_table('portfolio_skill_category_locale')
    op.drop_table('portfolio_site_locale')
    op.drop_table('portfolio_project_locale')
    op.drop_table('portfolio_category_skill')
    op.drop_table('portfolio_career_locale')
    op.drop_table('portfolio_skill_category')
    op.drop_table('portfolio_skill')
    op.drop_table('portfolio_site')
    op.drop_table('portfolio_project')
    op.drop_table('portfolio_locale')
    op.drop_index('ix_portfolio_career_experience_order', table_name='portfolio_career')
    op.drop_table('portfolio_career')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
